accepted = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "BSD-3-Clause",
    "ISC",
    "OpenSSL",
    "BSL-1.0",
    "curl",
    "Zlib",
]
targets = [
    "x86_64-unknown-linux-musl",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
no-clearly-defined = true

[private]
ignore = true

[linux-raw-sys.clarify]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"

[[linux-raw-sys.clarify.files]]
path = "LICENSE-APACHE"
license = "Apache-2.0"
checksum = "a60eea817514531668d7e00765731449fe14d059d3249e0bc93b36de45f759f2"

[[linux-raw-sys.clarify.files]]
path = "LICENSE-MIT"
license = "MIT"
checksum = "23f18e03dc49df91622fe2a76176497404e46ced8a715d9d2b67a7446571cca3"

[[linux-raw-sys.clarify.files]]
path = "LICENSE-Apache-2.0_WITH_LLVM-exception"
license = "Apache-2.0 WITH LLVM-exception"
checksum = "268872b9816f90fd8e85db5a28d33f8150ebb8dd016653fb39ef1f94f2686bc5"
